### ISSUE TITLE
Full File Path

### ISSUE THREAD

**Issue by shakeeb-mts** [felixzapata/gulp-checktextdomain#5]
Hi,

When there is an error it should show the full file path not only the file name. Easy to find the file. The Grunt module is doing that.

Thanks

**Comment by felixzapata** [comment]
Hi, I will take a look as soon as possible

**Comment by felixzapata** [comment]
@shakeeb-mts Done. Please check release 2.1.0

**Comment by shakeeb-mts** [comment]
Hi @felixzapata ,

Thanks for the prompt update man. That's great but you forget to concat the file name, path is there now but filename is missing. As previously filename is coming not the path.

![image](https://user-images.githubusercontent.com/22878349/32888261-838a14d2-cae8-11e7-8486-bc60fa25f203.png)

Thanks

**Comment by felixzapata** [comment]
hi, can you make a pull request?

**Comment by shakeeb-mts** [comment]
Yeah sure :)

**Comment by meshakeeb** [comment]
Hi @felixzapata here is the PR.

https://github.com/felixzapata/gulp-checktextdomain/pull/6

**Comment by felixzapata** [comment]
@meshakeeb done. Thanks
