### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by FrankM1** [felixzapata/gulp-checktextdomain#7]
Is there a way to exclude some directories or files? 

grunt-checktextdomain has a extra parameter 'files' that works like this: 

<pre>
    files: [ {
            src: [
                '**/*.php',
                '!node_modules/**',
                '!build/**',
                '!tests/**',
                '!.github/**',
                '!vendor/**',
                '!*~'
            ],
            expand: true
        } ]
</pre>

**Comment by felixzapata** [comment]
hi @FrankM1 you can use the similar pattern to ignore files and directories in your `gulp.src` task.

```gulp.task('default', function() {
  return gulp.src([
      'src/**/*',         //select all files
      '!src/**/_*/',      //exclude folders starting with '_'
      '!src/**/_*/**/*',  //exclude files/subfolders in folders starting with '_'
    ])
    .pipe(gulp.dest('dist'));
});
```

[Exclude Directory-Pattern in gulp with glob in `gulp.src`](https://medium.com/@jack.yin/exclude-directory-pattern-in-gulp-with-glob-in-gulp-src-9cc981f32116)

**Comment by FrankM1** [comment]
Thanks Felix, this is actually what I ended up using. Finally migrating all my projects to gulp. Keep up the good work.
