### ISSUE TITLE
The Problem with gulp-util

### ISSUE THREAD

**Issue by shakeeb-mts** [felixzapata/gulp-checktextdomain#8]
gulp-util is deprecated can you please fix it for gulp v4.

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by meshakeeb** [comment]
Hi @felixzapata ,

I fix the issue and generated a PR for it.

Thanks

**Comment by felixzapata** [comment]
hi @meshakeeb . Thanks for the pull request. I've released version 2.2.0

**Comment by shakeeb-mts** [comment]
You welcome @felixzapata I love this package save alot of time in big projects.

**Comment by meshakeeb** [comment]
You welcome @felixzapata I love this package save alot of time in big projects.
